["C1"]
"pdf file" = "C1_age.txt"
"prior" = "C1prior_age.txt"

["C2"]
"pdf file" = "C2_age.txt"
"prior" = "C2prior_age.txt"

["C3"]
"pdf file" = "C3_age.txt"
"prior" = "C3prior_age.txt"

["C5"]
"pdf file" = "C5_age.txt"
"prior" = "C5prior_age.txt"

["C6"]
"pdf file" = "C6_age.txt"
"prior" = "C6prior_age.txt"

["C7"]
"pdf file" = "C7_age.txt"
"prior" = "C7prior_age.txt"

["C8"]
"pdf file" = "C8_age.txt"
"prior" = "C8prior_age.txt"

["C10"]
"pdf file" = "C10_age.txt"
"prior" = "C10prior_age.txt"

["C11"]
"pdf file" = "C11_age.txt"
"prior" = "C11prior_age.txt"